### ISSUE TITLE
Incorrect token reference in hmanzur/actions-set-secret

### ISSUE THREAD

**Issue by tim-g-provectusalgae** [ericanastas/deploy-google-app-script-action#10]
https://github.com/ericanastas/deploy-google-app-script-action/blob/051d5732de716820b4f928bd9f9e3befd7441f80/.github/workflows/deploy-script.yml#L47

Should be `token: ${{ secrets.CLASPRC_JSON }}`

**Comment by ericanastas** [comment]
No it shouldn't.   
  
`token` is the token used to access the github repo and thus should be set to `REPO_ACCESS_TOKEN`
