### ISSUE TITLE
License this code

### ISSUE THREAD

**Issue by iansan5653** [ericanastas/deploy-google-app-script-action#8]
Hello, I'd like to adapt your work into my Google Apps Script template repository, but I can't legally do that because the code is not licensed for reuse.

Could you add a `license.md` file with a formal license?  Here's details on how to do that: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by ianhyzy** [comment]
Bumping this

**Comment by ericanastas** [comment]
@iansan5653 @ianhyzy   
  
Done! a3dd7d1
